### PR TITLE
updated card UI for Portal

### LINKED ISSUE #95: Update Card UI to match current design match
https://www.figma.com/file/57YjrQC68v5QNqVfctd1mY/TD21?node-id=0%3A1

- [x] Update Style File (ask jack)
- [x] Update Card UI to match thing
- [x] Bonus: Fix the timing logic (if you want)

### PR DESCRIPTION
**Pull request by tatiaris**
Redesigned the Card UI to match the theme according to the Figma.
closes #95

### CODE REVIEW

**Comment by geooot** [comment]
Isn't the arrow in the wrong place? @tatiaris 
Also the animation is a bit slow

**Comment by tatiaris** [comment]
> Isn't the arrow in the wrong place? @tatiaris
> Also the animation is a bit slow

I placed the arrow based on the figma, I can change the padding/positioning if you'd like.
I'll make the animation 2x faster (unless you have a recommended speed)

**Comment by danabreo** [comment]
nit: on load, I can see the hovering arrows disappear, is there any way to have them hidden on load?

**Comment by tatiaris** [comment]
> nit: on load, I can see the hovering arrows disappear, is there any way to have them hidden on load?

i'll try messing around to see what's causing it and if it's avoidable

**Comment by tatiaris** [comment]
@danabreo thank you for that nitpick, it lead to some obvious realizations which led to 10x cleaner code. And it fixed the on load animation. Lmk if there's anything else that can be better

**Comment by danabreo** [comment]
> @danabreo thank you for that nitpick, it lead to some obvious realizations which led to 10x cleaner code. And it fixed the on load animation. Lmk if there's anything else that can be better

now both triangles appear on hover. I believe the desired animation was to have the left triangle (behind the arrow) be permanent, and have the right appear on hover. lmk if both appearing is intentional.

**Comment by tatiaris** [comment]
> > @danabreo thank you for that nitpick, it lead to some obvious realizations which led to 10x cleaner code. And it fixed the on load animation. Lmk if there's anything else that can be better
> 
> now both triangles appear on hover. I believe the desired animation was to have the left triangle (behind the arrow) be permanent, and have the right appear on hover. lmk if both appearing is intentional.

Yea the both appearing was intentional because there's a thin line that appears if the image is kept static due to some pixels in the image not being perfect.

I also made another small change in the way the clip path for the cover changes which I forgot to do in the previous edit. Everything lgtm right now even at 10s transition speed.

If there's nothing else, I'll merge the PR

**Review by danabreo — APPROVED** [review]

**Pull request merged**
